language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install .
  - pip install -r tests/test_requirements.txt
# command to run tests
script:
    if [[ $TRAVIS_PYTHON_VERSION < 3.5 ]]; then py.test;else pytest; fi
